### ISSUE TITLE
Auto Reindex Website

### ISSUE THREAD

**Issue by anchormansam** [JMStewart00/bangachain#7]
Need the site to reindex (There is a bug but doing this will be a bandaid till thats fixed)

Setup to run every 

option 1) Monday/Wednesday/Friday
option 2) Daily
option 3) Nightly

**Comment by JMStewart00** [comment]
Cron was previously only running once a day which is why some of the issues we were seeing were happening.

So let’s keep an eye on the site for some bogging down. Cron was running only once a day and I just upped it to run every three hours to help with some of these indexing issues we’ve seen. Additionally, if something is not in search but you think it should be we can always visit this link to try to force it. It’s a manual cron run via /admin/config/system/cron.

We can reopen if we feel the need to do so.
